spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doancntt1
    username: root
    password: leloc123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect  # Thêm dòng này
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
  jwt:
    secret: Y2X2QmxJX09tV5NmdQRWbJ0Amk2pv5Kgd7XqfVKlD67RwrJkwqprFDmNlzfgeu4z
    expiration: 3600000  # Thời gian tồn tại token (ms), ở đây là 1 giờ
server:
  port: 8888
